"""Write the logo and the cat's shapes into the web app, and render the icons.

Run from the logo workspace (the folder holding popcat/, see README.md) after morph.py:

  python <repo>/tools/logo/export.py <repo>

Outputs (all generated; edit the pipeline, not these files):
  src/memeseeks/web/popcat.js           the cat's shapes for every animation (window.POPCAT)
  src/memeseeks/web/icons/logo.svg      the logo, transparent (favicon, and the page's own logo)
  src/memeseeks/web/icons/icon-*.png    PWA / home-screen icons (any + maskable), apple-touch-icon
  tools/logo/memeseeks.ico              the desktop launcher's icon
Needs: pip install resvg-py pillow
"""

import importlib.util
import io
import json
import sys
from pathlib import Path

import resvg_py
from PIL import Image

repo = Path(sys.argv[1]).resolve()
here = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("b6", here / "build6.py")
b6 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(b6)  # the logo drawing (art, bubble, box)

m = json.loads(Path("popcat/morph-inline.json").read_text(encoding="utf-8"))
web = repo / "src" / "memeseeks" / "web"
(web / "icons").mkdir(parents=True, exist_ok=True)

# ---- the shapes the page animates ----
data = {"vb": m["vb"], "body": m["body"], "closed": m["paths"]["closed"], "final": m["paths"]["logo"],
        "bubble": m["bubble"], "mc": [round(v, 1) for v in m["mouth_c"]]}
(web / "popcat.js").write_text(
    "// Generated by tools/logo/export.py from the logo pipeline: do not edit by hand.\n"
    "// The Pop Cat's shapes: the logo (final) and the closed mouth (closed) share one command list per shape,\n"
    "// so any state in between is the numbers interpolated (see the cat module in app.js).\n"
    f"window.POPCAT = {json.dumps(data, ensure_ascii=False, separators=(',', ':'))};\n", encoding="utf-8")

# ---- the logo as a standalone SVG ----
VX, VY, VS = (float(v) for v in m["vb"].split()[:3])
logo_svg = f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{m["vb"]}">{b6.art()}</svg>\n'
(web / "icons" / "logo.svg").write_text(logo_svg, encoding="utf-8")


def tile(bg, scale):
    """The logo on a square background, the cat taking `scale` of the side (centred)."""
    pad = VS * (1 / scale - 1) / 2
    vb = f"{VX - pad:.0f} {VY - pad:.0f} {VS + 2 * pad:.0f} {VS + 2 * pad:.0f}"
    rect = f'<rect x="{VX - pad:.0f}" y="{VY - pad:.0f}" width="{VS + 2 * pad:.0f}" height="{VS + 2 * pad:.0f}" fill="{bg}"/>' if bg else ""
    return f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}">{rect}{b6.art()}</svg>'


def png(svg, size):
    return Image.open(io.BytesIO(bytes(resvg_py.svg_to_bytes(svg_string=svg, width=size, height=size)))).convert("RGBA")


PAPER = "#F3EFE4"
png(tile(PAPER, 0.86), 192).save(web / "icons" / "icon-192.png")
png(tile(PAPER, 0.86), 512).save(web / "icons" / "icon-512.png")
png(tile(PAPER, 0.68), 512).save(web / "icons" / "icon-maskable-512.png")   # inside the 80% safe zone
png(tile(PAPER, 0.80), 180).convert("RGB").save(web / "icons" / "apple-touch-icon.png")
sizes = [16, 24, 32, 48, 64, 128, 256]
ico = [png(tile(None, 0.96), s) for s in sizes]
ico[-1].save(here / "memeseeks.ico", sizes=[(s, s) for s in sizes], append_images=ico[:-1])
print("wrote popcat.js, icons/ and memeseeks.ico")
